server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zxc47POI!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    com.zhouyi.book: debug
  file: logs/debug.log
